management:
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: otlp-tracing-example

logging:
#  level:
#    org:
#      springframework: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-}, spanId=%X{spanId:-}]"